# Generated by Django 5.0 on 2023-12-19 11:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0011_alter_product_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='brands',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='brand_category', to='home.category'),
        ),
    ]
