# Generated by Django 5.0 on 2023-12-26 16:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0013_category_size'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='size',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='category_size', to='home.size'),
        ),
    ]
